/*
============================================================
MERISKILL INTERNSHIP PROJECT — SALES ANALYSIS
============================================================

This analysis explores 2019 sales data to understand order
trends, product performance, revenue, and sales performance
across different locations.

The analysis focuses on:
1. Sales performance over time
2. Product performance
3. Overall revenue
4. Revenue by location

The original analysis was preserved where technically sound.
A consistent 2019 date filter has been applied throughout
the workflow.
*/


/* ============================================================
   Q1. MONTHLY ORDER TREND
   ============================================================
  
-- Review the number of distinct orders recorded each month
   to understand how order activity changed during 2019.
*/

SELECT
    MONTH(order_date) AS month,
    COUNT(DISTINCT order_id) AS order_count
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date);

/*
   FINDING:
   Order activity varied throughout the year, with stronger
   activity toward the end of the year. December recorded
   the highest monthly order volume.
*/


/* ============================================================
   Q2. QUARTERLY ORDER TREND
   ============================================================
   
-- Summarize distinct orders by quarter to provide a broader
   view of sales activity during the year.
*/

SELECT
    QUARTER(order_date) AS quarter,
    COUNT(DISTINCT order_id) AS order_count
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY QUARTER(order_date)
ORDER BY QUARTER(order_date);

/*
   FINDING:
   The fourth quarter recorded the highest order volume,
   supporting the stronger activity observed toward the end
   of the year.
*/


/* ============================================================
   Q3. PRODUCT PERFORMANCE BY ORDER COUNT
   ============================================================
  
-- Identify which products appeared in the highest number
   of distinct orders.
*/

SELECT
    product AS product_category,
    COUNT(DISTINCT order_id) AS order_count
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY product
ORDER BY order_count DESC;

/*
   FINDING:
   Lower-priced accessories appeared frequently across
   customer orders, with the USB-C Charging Cable recording
   the highest distinct order count.
*/


/* ============================================================
   Q4. PRODUCT PERFORMANCE BY REVENUE
   ============================================================
   
-- Compare the revenue generated by each product to identify
   the strongest revenue contributors.
*/

SELECT
    product AS product_category,
    SUM(sales) AS revenue
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY product
ORDER BY revenue DESC;

/*
   FINDING:
   Higher-priced products contributed more strongly to
   revenue. The MacBook Pro Laptop generated the highest
   product revenue despite lower order frequency than
   several accessories.
*/


/* ============================================================
   Q5. PRODUCT PERFORMANCE BY QUANTITY ORDERED
   ============================================================
   
-- Compare the total units ordered for each product during
   the 2019 analysis period.
*/

SELECT
    product AS product_category,
    SUM(quantity_ordered) AS quantity_ordered
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY product
ORDER BY quantity_ordered DESC;

/*
   FINDING:
   Batteries and charging accessories accounted for much of
   the unit volume. AAA Batteries (4-pack) recorded the
   highest quantity in the original analysis.
*/


/* ============================================================
   Q6. OVERALL SALES REVENUE
   ============================================================
  
-- Calculate the total sales revenue generated during the
   2019 analysis period.
*/

SELECT
    SUM(sales) AS total_revenue
FROM sales_data
WHERE order_date < '2020-01-01';

/*
   FINDING:
   The analysis recorded approximately $34.48 million in
   total sales revenue for the period.
*/


/* ============================================================
   Q7. REVENUE BY CITY
   ============================================================
   
-- Compare sales revenue across cities to identify the
   locations contributing most strongly to overall revenue.
*/

SELECT
    city,
    SUM(sales) AS revenue
FROM sales_data
WHERE order_date < '2020-01-01'
GROUP BY city
ORDER BY revenue DESC;

/*
   FINDING:
   San Francisco was the strongest revenue-generating city
   in the original analysis, followed by Los Angeles and
   New York City.
*/


/*
============================================================
OVERALL FINDING
============================================================

The sales analysis showed stronger order activity toward
the end of the year, particularly in the fourth quarter.
Product performance also differed according to their usage
measure: frequently ordered accessories contributed strongly
to order and unit volume, while higher-priced products
generated the most revenue. San Francisco was the leading
city by sales revenue in the original analysis.
*/
